/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_emery_andfixframwork_FixManager */

#ifndef _Included_com_example_emery_andfixframwork_FixManager
#define _Included_com_example_emery_andfixframwork_FixManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emery_andfixframwork_FixManager
 * Method:    replace
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_andfixframwork_FixManager_replace
  (JNIEnv *, jobject,jint ,jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
